/// Dimension table providing comprehensive date attributes for time-based analysis. Contains one row per calendar day with 30 columns covering calendar periods (year/month/day), fiscal periods, week calculations, offset fields for relative filtering, and formatted date labels. Essential for all time intelligence calculations and enables period-over-period comparisons. Relates to Sales table via OrderDate.
table Date
	lineageTag: 95132716-21a8-4aca-bc91-d1d0656071eb

	/// Primary date column containing each individual calendar day. This is the key column used to relate the Date table to fact tables. All date-based filtering and time intelligence calculations rely on this column being properly marked as a date type.
	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8d8c3612-1ecd-4320-b7cc-d0e46fb6fbac
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Four-digit year number (e.g., 2023, 2024). Extracted from the Date column using Date.Year function. Used for year-level aggregations, year-over-year comparisons, and filtering data by year.
	column Year
		dataType: int64
		formatString: 0
		lineageTag: a8d746cc-9d17-4a89-ae5c-37341c75de3e
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	/// The first day of the year (January 1st) for each date. Calculated using Date.StartOfYear function. Useful for creating year-to-date calculations and identifying year boundaries in visualizations.
	column 'Start of Year'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 68ec0a9d-7844-4761-96d3-707cb9d59d4e
		summarizeBy: none
		sourceColumn: Start of Year

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// The last day of the year (December 31st) for each date. Calculated using Date.EndOfYear function. Used for year-end analysis and determining if a date falls at year boundaries.
	column 'End of Year'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 93c968cd-7577-47ce-8285-2f66e2c7b568
		summarizeBy: none
		sourceColumn: End of Year

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Month number from 1 (January) to 12 (December). Extracted from the Date column using Date.Month function. Used for month-level aggregations and creating month-based reports. Should be combined with Year for unique identification.
	column Month
		dataType: int64
		formatString: 0
		lineageTag: 36767c19-b3d2-4364-bde3-ad5a361cf672
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	/// The first day of the month for each date. Calculated using Date.StartOfMonth function. Essential for month-to-date calculations and identifying month boundaries in time series analysis.
	column 'Start of Month'
		dataType: dateTime
		formatString: Long Date
		lineageTag: e0080fdf-07b7-4d0e-a26c-4ec8d1c23ffd
		summarizeBy: none
		sourceColumn: Start of Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// The last day of the month for each date. Calculated using Date.EndOfMonth function. Used for end-of-month analysis and determining the number of days remaining in a month.
	column 'End of Month'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d04cebc0-4b2e-4519-86e8-adc37595fe4b
		summarizeBy: none
		sourceColumn: End of Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Total number of days in the month (28-31 depending on month and leap year). Calculated using Date.DaysInMonth function. Useful for daily average calculations and understanding month length variations.
	column 'Days in Month'
		dataType: int64
		formatString: 0
		lineageTag: 90ab0594-746c-4e46-98fa-ef5baaebb8a3
		summarizeBy: none
		sourceColumn: Days in Month

		annotation SummarizationSetBy = Automatic

	/// Day of the month number from 1 to 31. Extracted from the Date column using Date.Day function. Used for day-level filtering and creating day-of-month analysis like sales by day number.
	column Day
		dataType: int64
		formatString: 0
		lineageTag: f218bf8e-dbdc-4402-b8e7-ebf3fa34b5a6
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	/// Full name of the day of the week (Monday, Tuesday, etc.). Generated using Date.DayOfWeekName function. Used for weekday analysis, identifying patterns by day name, and creating user-friendly reports.
	column 'Day Name'
		dataType: string
		lineageTag: ce1ed5c2-2d86-42aa-9baf-c2526448fbc0
		summarizeBy: none
		sourceColumn: Day Name

		annotation SummarizationSetBy = Automatic

	/// Numeric day of the week where Monday=0, Tuesday=1, through Sunday=6 (based on firstDayofWeek setting). Calculated using Date.DayOfWeek function. Useful for sorting weekdays correctly and weekday-based aggregations.
	column 'Day of Week'
		dataType: int64
		formatString: 0
		lineageTag: b2017c36-d966-402f-a605-f1c48712a1db
		summarizeBy: none
		sourceColumn: Day of Week

		annotation SummarizationSetBy = Automatic

	/// Sequential day number within the year from 1 to 365 (or 366 in leap years). Calculated using Date.DayOfYear function. Useful for year-over-year same-day comparisons and seasonal analysis.
	column 'Day of Year'
		dataType: int64
		formatString: 0
		lineageTag: f1b5fc8f-a967-4d51-ad5f-4882cbfda083
		summarizeBy: none
		sourceColumn: Day of Year

		annotation SummarizationSetBy = Automatic

	/// Full name of the month (January, February, etc.). Generated using Date.MonthName function. Provides user-friendly month labels for reports and should be sorted by Month number, not alphabetically.
	column 'Month Name'
		dataType: string
		lineageTag: f1a03c7c-691b-4a92-9bca-4ac77495280a
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	/// Quarter number from 1 to 4 representing calendar quarters (Q1=Jan-Mar, Q2=Apr-Jun, Q3=Jul-Sep, Q4=Oct-Dec). Calculated using Date.QuarterOfYear function. Essential for quarterly reporting and quarter-over-quarter analysis.
	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: 4f52d191-bfa5-4b10-b7c1-b0018345abdd
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	/// The first day of the quarter for each date. Calculated using Date.StartOfQuarter function. Used for quarter-to-date calculations and identifying quarter boundaries in reports.
	column 'Start of Quarter'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 47b992c7-658f-463f-911c-1abebe0a8066
		summarizeBy: none
		sourceColumn: Start of Quarter

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// The last day of the quarter for each date. Calculated using Date.EndOfQuarter function. Useful for end-of-quarter analysis and determining quarter completion status.
	column 'End of Quarter'
		dataType: dateTime
		formatString: Long Date
		lineageTag: cb29e565-af54-4e0c-989c-f3821fb9d5c8
		summarizeBy: none
		sourceColumn: End of Quarter

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Week number within the year from 1 to 52/53. Calculated using Date.WeekOfYear function based on the firstDayofWeek setting. Used for weekly trending and week-over-week comparisons.
	column 'Week of Year'
		dataType: int64
		formatString: 0
		lineageTag: dac1d08b-d91c-4100-9dc2-f2f7b9f429d5
		summarizeBy: none
		sourceColumn: Week of Year

		annotation SummarizationSetBy = Automatic

	/// Week number within the month from 1 to 5. Calculated using Date.WeekOfMonth function. Helps identify which week of the month a date falls into for intra-month pattern analysis.
	column 'Week of Month'
		dataType: int64
		formatString: 0
		lineageTag: cd3032dc-b811-4859-af07-0eead6887a08
		summarizeBy: none
		sourceColumn: Week of Month

		annotation SummarizationSetBy = Automatic

	/// The first day of the week (typically Monday) for each date. Calculated using Date.StartOfWeek function. Essential for week-to-date calculations and creating weekly aggregations.
	column 'Start of Week'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 94f79b9d-4a69-480e-8a6e-48509af7e73b
		summarizeBy: none
		sourceColumn: Start of Week

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// The last day of the week (typically Sunday) for each date. Calculated using Date.EndOfWeek function. Used for end-of-week reporting and determining if a date is at week boundaries.
	column 'End of Week'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7f964294-a064-4ab9-a592-a39667851289
		summarizeBy: none
		sourceColumn: End of Week

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Fiscal year number adjusted based on the fiscal year start month (configured as month 7/July). Calculated by shifting dates forward by the fiscal adjustment period before extracting the year. Used when business reporting follows a non-calendar fiscal year.
	column 'Fiscal Year'
		dataType: int64
		formatString: 0
		lineageTag: 299bd2fe-c4b8-4b7b-9a1b-a2997e205ce7
		summarizeBy: none
		sourceColumn: Fiscal Year

		annotation SummarizationSetBy = Automatic

	/// Fiscal quarter number (1-4) adjusted for the fiscal year calendar. Calculated after applying the fiscal month offset to align with company's fiscal year structure. Use this instead of calendar Quarter for fiscal reporting.
	column 'Fiscal Quarter'
		dataType: int64
		formatString: 0
		lineageTag: be121ea5-c1a3-43eb-bc59-d9e1373b0e34
		summarizeBy: none
		sourceColumn: Fiscal Quarter

		annotation SummarizationSetBy = Automatic

	/// Fiscal month number adjusted for the fiscal year calendar. Calculated after applying the fiscal month offset to align quarters and months with the fiscal year start. Essential for fiscal period-based analysis.
	column 'Fiscal Month'
		dataType: int64
		formatString: 0
		lineageTag: b5904ab6-01ec-4ec8-b147-e13e7ebd7f00
		summarizeBy: none
		sourceColumn: Fiscal Month

		annotation SummarizationSetBy = Automatic

	/// Number of days between each date and today's date. Negative values are past dates (e.g., -30 = 30 days ago), positive values are future dates. Calculated as Date - Today. Useful for relative date filtering like 'Last 30 Days' or 'Next 7 Days'.
	column 'Day Offset'
		dataType: int64
		formatString: 0
		lineageTag: 2c3da168-3b5d-483c-a3dd-5377ad33723f
		summarizeBy: none
		sourceColumn: Day Offset

		annotation SummarizationSetBy = Automatic

	/// Number of months between each date and the current month. Negative values are past months (e.g., -3 = 3 months ago), zero is current month, positive values are future months. Calculated as (Year-CurrentYear)*12 + (Month-CurrentMonth). Essential for relative period filtering.
	column 'Month Offset'
		dataType: int64
		formatString: 0
		lineageTag: 55afd681-ebf2-4e54-be07-5a697433435f
		summarizeBy: none
		sourceColumn: Month Offset

		annotation SummarizationSetBy = Automatic

	/// Number of years between each date and the current year. Negative values are past years (e.g., -1 = last year), zero is current year, positive values are future years. Calculated as Year - CurrentYear. Used for dynamic year filtering like 'Last Year' or 'Current Year'.
	column 'Year Offset'
		dataType: int64
		formatString: 0
		lineageTag: f67ea620-57f4-4a9d-bbd2-ad7de997d4ff
		summarizeBy: none
		sourceColumn: Year Offset

		annotation SummarizationSetBy = Automatic

	/// Number of quarters between each date and the current quarter. Negative values are past quarters (e.g., -2 = 2 quarters ago), zero is current quarter. Calculated as (Year-CurrentYear)*4 + (Quarter-CurrentQuarter). Enables relative quarter filtering like 'Last 4 Quarters'.
	column 'Quarter Offset'
		dataType: int64
		formatString: 0
		lineageTag: c38def61-4068-4c4a-98b3-a3ab5394f559
		summarizeBy: none
		sourceColumn: Quarter Offset

		annotation SummarizationSetBy = Automatic

	/// Human-readable year-month label formatted as 'MMM yyyy' (e.g., 'Jan 2024', 'Feb 2024'). Created using Date.ToText function. Provides user-friendly month labels that combine month name and year for reports and axes labels.
	column Year-Month
		dataType: string
		lineageTag: 09428cae-a0ef-426b-90f8-3bed3a65b692
		summarizeBy: none
		sourceColumn: Year-Month

		annotation SummarizationSetBy = Automatic

	/// Numeric year-month code in YYYYMM format (e.g., 202401 for January 2024). Created using Date.ToText function. Useful for sorting months chronologically and creating unique month identifiers that sort correctly.
	column 'Year-Month Code'
		dataType: int64
		formatString: 0
		lineageTag: 130dc57c-403c-4690-9560-20bd1994f44f
		summarizeBy: none
		sourceColumn: Year-Month Code

		annotation SummarizationSetBy = Automatic

	/// Special comparison date that shifts dates back by one year if they're older than 2 years from today. Returns the original date if within last year, adds 365 days if 1-2 years old, null if older. Used for year-over-year comparisons that align dates across years.
	column 'Date Equalizer'
		dataType: string
		lineageTag: 76d9159e-d401-4d28-a496-8c95b02354f0
		summarizeBy: none
		sourceColumn: Date Equalizer

		annotation SummarizationSetBy = Automatic

	partition Date = m
		mode: import
		source = ```
				let
				// configurations start
				    Today=Date.From(DateTime.LocalNow()), // today's date
				    FromYear = 2023,//set the start year of the date dimension. dates start from 1st of January of this year        
				    ToYear= Date.Year(Today),// set the end year of the date dimension. dates end at 31st of December of this year
				    StartofFiscalYear=7, // set the month number that is start of the financial year. example; if fiscal year start is July, value is 7
				    firstDayofWeek=Day.Monday, // set the week's start day, values: Day.Monday, Day.Sunday....
				// configuration end
				    
				    FromDate=#date(FromYear,1,1),
				    ToDate = Today,
				    Source=List.Dates(
				        FromDate,
				        Duration.Days(ToDate-FromDate)+1,
				        #duration(1,0,0,0)
				    ),
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Date"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date", type date}}),
				    #"Inserted Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Inserted Start of Year" = Table.AddColumn(#"Inserted Year", "Start of Year", each Date.StartOfYear([Date]), type date),
				    #"Inserted End of Year" = Table.AddColumn(#"Inserted Start of Year", "End of Year", each Date.EndOfYear([Date]), type date),
				    #"Inserted Month" = Table.AddColumn(#"Inserted End of Year", "Month", each Date.Month([Date]), Int64.Type),
				    #"Inserted Start of Month" = Table.AddColumn(#"Inserted Month", "Start of Month", each Date.StartOfMonth([Date]), type date),
				    #"Inserted End of Month" = Table.AddColumn(#"Inserted Start of Month", "End of Month", each Date.EndOfMonth([Date]), type date),
				    #"Inserted Days in Month" = Table.AddColumn(#"Inserted End of Month", "Days in Month", each Date.DaysInMonth([Date]), Int64.Type),
				    #"Inserted Day" = Table.AddColumn(#"Inserted Days in Month", "Day", each Date.Day([Date]), Int64.Type),
				    #"Inserted Day Name" = Table.AddColumn(#"Inserted Day", "Day Name", each Date.DayOfWeekName([Date]), type text),
				    #"Inserted Day of Week" = Table.AddColumn(#"Inserted Day Name", "Day of Week", each Date.DayOfWeek([Date],firstDayofWeek), Int64.Type),
				    #"Inserted Day of Year" = Table.AddColumn(#"Inserted Day of Week", "Day of Year", each Date.DayOfYear([Date]), Int64.Type),
				    #"Inserted Month Name" = Table.AddColumn(#"Inserted Day of Year", "Month Name", each Date.MonthName([Date]), type text),
				    #"Inserted Quarter" = Table.AddColumn(#"Inserted Month Name", "Quarter", each Date.QuarterOfYear([Date]), Int64.Type),
				    #"Inserted Start of Quarter" = Table.AddColumn(#"Inserted Quarter", "Start of Quarter", each Date.StartOfQuarter([Date]), type date),
				    #"Inserted End of Quarter" = Table.AddColumn(#"Inserted Start of Quarter", "End of Quarter", each Date.EndOfQuarter([Date]), type date),
				    #"Inserted Week of Year" = Table.AddColumn(#"Inserted End of Quarter", "Week of Year", each Date.WeekOfYear([Date],firstDayofWeek), Int64.Type),
				    #"Inserted Week of Month" = Table.AddColumn(#"Inserted Week of Year", "Week of Month", each Date.WeekOfMonth([Date],firstDayofWeek), Int64.Type),
				    #"Inserted Start of Week" = Table.AddColumn(#"Inserted Week of Month", "Start of Week", each Date.StartOfWeek([Date],firstDayofWeek), type date),
				    #"Inserted End of Week" = Table.AddColumn(#"Inserted Start of Week", "End of Week", each Date.EndOfWeek([Date],firstDayofWeek), type date),
				    FiscalMonthBaseIndex=13-StartofFiscalYear,
				    adjustedFiscalMonthBaseIndex=if(FiscalMonthBaseIndex>=12 or FiscalMonthBaseIndex<0) then 0 else FiscalMonthBaseIndex,
				    #"Added Fiscal Base Date" = Table.AddColumn(#"Inserted End of Week", "FiscalBaseDate", each Date.AddMonths([Date],adjustedFiscalMonthBaseIndex)),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Fiscal Base Date",{{"FiscalBaseDate", type date}}),
				    #"Inserted Year1" = Table.AddColumn(#"Changed Type1", "Year.1", each Date.Year([FiscalBaseDate]), Int64.Type),
				    #"Renamed Fiscal Year" = Table.RenameColumns(#"Inserted Year1",{{"Year.1", "Fiscal Year"}}),
				    #"Inserted Quarter1" = Table.AddColumn(#"Renamed Fiscal Year", "Quarter.1", each Date.QuarterOfYear([FiscalBaseDate]), Int64.Type),
				    #"Renamed Fiscal Quarter" = Table.RenameColumns(#"Inserted Quarter1",{{"Quarter.1", "Fiscal Quarter"}}),
				    #"Inserted Month1" = Table.AddColumn(#"Renamed Fiscal Quarter", "Month.1", each Date.Month([FiscalBaseDate]), Int64.Type),
				    #"Renamed Fiscal Month" = Table.RenameColumns(#"Inserted Month1",{{"Month.1", "Fiscal Month"}}),
				    #"Removed FiscalBaseDate" = Table.RemoveColumns(#"Renamed Fiscal Month",{"FiscalBaseDate"}),
				    #"Inserted Age" = Table.AddColumn(#"Removed FiscalBaseDate", "Age", each [Date]-Today, type duration),
				    #"Extracted Days" = Table.TransformColumns(#"Inserted Age",{{"Age", Duration.Days, Int64.Type}}),
				    #"Renamed Day Offset" = Table.RenameColumns(#"Extracted Days",{{"Age", "Day Offset"}}),
				    #"Added Month Offset" = Table.AddColumn(#"Renamed Day Offset", "Month Offset", each (([Year]-Date.Year(Today))*12)
				+([Month]-Date.Month(Today))),
				    #"Added Year Offset" = Table.AddColumn(#"Added Month Offset", "Year Offset", each [Year]-Date.Year(Today)),
				    #"Added Quarter Offset" = Table.AddColumn(#"Added Year Offset", "Quarter Offset", each (([Year]-Date.Year(Today))*4)
				+([Quarter]-Date.QuarterOfYear(Today))),
				    #"Added Year-Month" = Table.AddColumn(#"Added Quarter Offset", "Year-Month", each Date.ToText([Date],"MMM yyyy")),
				    #"Added Year-Month Code" = Table.AddColumn(#"Added Year-Month", "Year-Month Code", each Date.ToText([Date],"yyyyMM")),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Year-Month Code",{{"Month Offset", Int64.Type}, {"Year Offset", Int64.Type}, {"Quarter Offset", Int64.Type}, {"Year-Month Code", Int64.Type}}),
				    #"Added Date Equalizer" = Table.AddColumn(#"Changed Type2", "Date Equalizer", each if [Day Offset] > -365 then [Date] else if [Day Offset] > -730 then Date.AddDays([Date],365) else null)
				in
				    #"Added Date Equalizer"
				```

	changedProperty = Name

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

